spring:
  application:
    name: cards-game
  h2:
    console:
      enabled: true
      path: /h2console
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  port: 8888
  servlet:
    context-path: /4horsemen
    application-display-name: 4horsemen



